# ============ BUILDER ============
FROM golang:1.21.13 AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    git ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# Sadece GitHub token
ARG GITHUB_TOKEN

ARG TARGET_SERVICE=bff
ENV TARGET_SERVICE=${TARGET_SERVICE}

# Docker build'de username/password sormasın
ENV GIT_TERMINAL_PROMPT=0

# GitHub HTTPS URL'lerini token'lı hale getir (submodule clone için)
RUN git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

WORKDIR /opt/data/teamgram

COPY .git .git
COPY .gitmodules .gitmodules

RUN git submodule sync --recursive \
 && git submodule update --init --recursive

COPY . .

RUN chmod +x ./build-enterprise-phone.sh && ./build-enterprise-phone.sh ${TARGET_SERVICE}


# ============ RUNTIME ============
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    ffmpeg \
    coturn \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/data/teamgram

COPY --from=builder /opt/data/teamgram/bin /opt/data/teamgram/bin
COPY --from=builder /opt/data/teamgram/etc /opt/data/teamgram/etc2
COPY --from=builder /opt/data/teamgram/bin/server_pkcs1.key /opt/data/teamgram/bin/

RUN mkdir -p /opt/data/teamgram/logs

ARG TARGET_SERVICE=bff
ENV TARGET_SERVICE=${TARGET_SERVICE}

WORKDIR /opt/data/teamgram/bin
CMD ["sh", "-c", "./${TARGET_SERVICE} -f=../etc2/${TARGET_SERVICE}.yaml"]
